# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
variables:
 tag: $(build.buildId)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: Docker@2
  inputs:
    containerRegistry: 'DockerTest'
    repository: 'abhiraj1289/testing'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: KubernetesManifest@1
  inputs:
    action: 'deploy'
    connectionType: 'kubernetesServiceConnection'
    kubernetesServiceConnection: 'AKS'
    namespace: 'default'
    manifests: '**/deploy.yaml'
    containers: 'abhiraj1289/testing:$(tag)'