pool:
  name: Azure Pipelines
variables:
  tag: $(build.buildId)
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: AzureC
    azureContainerRegistry: '{"loginServer":"abhiraj.azurecr.io", "id" : "/subscriptions/dd6c6bf8-a03a-4827-8b1c-665b173f14fa/resourceGroups/AzureStudent/providers/Microsoft.ContainerRegistry/registries/abhiraj"}'

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: AzureC
    azureContainerRegistry: '{"loginServer":"abhiraj.azurecr.io", "id" : "/subscriptions/dd6c6bf8-a03a-4827-8b1c-665b173f14fa/resourceGroups/AzureStudent/providers/Microsoft.ContainerRegistry/registries/abhiraj"}'
    action: 'Push an image'

- task: KubernetesManifest@1
  displayName: deploy
  inputs:
    kubernetesServiceConnection: AKS
    namespace: default
    manifests: deploy.yaml
    containers: 'abhiraj.azurecr.io/abhi98211/$(tag)'

